-- 営業日データの簡単な追加方法
-- 来月の営業日を5日分追加

USE clinic_booking_db;

-- 既存の営業日を確認
SELECT * FROM business_days;

-- 来月の営業日を追加（重複チェック付き）
INSERT INTO business_days (business_date, is_available) 
VALUES 
(DATE_ADD(CURDATE(), INTERVAL 1 MONTH), TRUE),
(DATE_ADD(CURDATE(), INTERVAL 1 MONTH) + INTERVAL 1 DAY, TRUE),
(DATE_ADD(CURDATE(), INTERVAL 1 MONTH) + INTERVAL 2 DAY, TRUE),
(DATE_ADD(CURDATE(), INTERVAL 1 MONTH) + INTERVAL 3 DAY, TRUE),
(DATE_ADD(CURDATE(), INTERVAL 1 MONTH) + INTERVAL 4 DAY, TRUE),
(DATE_ADD(CURDATE(), INTERVAL 1 MONTH) + INTERVAL 5 DAY, TRUE),
(DATE_ADD(CURDATE(), INTERVAL 1 MONTH) + INTERVAL 6 DAY, TRUE),
(DATE_ADD(CURDATE(), INTERVAL 1 MONTH) + INTERVAL 7 DAY, TRUE),
(DATE_ADD(CURDATE(), INTERVAL 1 MONTH) + INTERVAL 8 DAY, TRUE),
(DATE_ADD(CURDATE(), INTERVAL 1 MONTH) + INTERVAL 9 DAY, TRUE)
ON DUPLICATE KEY UPDATE is_available = TRUE;

-- 確認
SELECT * FROM business_days ORDER BY business_date;
